
# Generated by CodiumAI

import json

import pytest

from marc21 import get_dictionary


class TestGetDictionary:

    #  Returns a JSON string representation of a dictionary.
    def test_returns_json_string_representation(self):
        # Given

        # When
        result = get_dictionary()

        # Then
        assert result != ''

        try:
            json.loads(result)
        except ValueError as e:
            pytest.fail(f"Unexpected exception raised: {e}")
